Process Process-1:
Traceback (most recent call last):
  File "/home/black/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/black/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/black/Data/GIT/OptimizeDemandResponse/Profit-Optimizer-A3C/modules/Agent.py", line 301, in train
    self.calculateAndUpdateL_C()
  File "/media/black/Data/GIT/OptimizeDemandResponse/Profit-Optimizer-A3C/modules/Agent.py", line 450, in calculateAndUpdateL_C
    self.god._updateCritc(loss/self.trajectoryLength)
  File "/media/black/Data/GIT/OptimizeDemandResponse/Profit-Optimizer-A3C/modules/Agent.py", line 139, in _updateCritc
    loss.backward()
  File "/home/black/.local/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/black/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
